### ISSUE TITLE
Problems about hyperbolic distance.

### ISSUE THREAD

**Issue by swt-user** [HazyResearch/KGEmb#10]
1. In your Class BaseH(KGModel):
  `def get_rhs(self, queries, eval_mode):
        """Get embeddings and biases of target entities."""
        if eval_mode:
            return self.entity.weight, self.bt.weight
        else:
            return self.entity(queries[:, 2]), self.bt(queries[:, 2])`
    I don't know for sure that maybe they should be mapped to hyperbolic space.
2.  In your Function `def hyp_distance_multi_c(x, v, c, eval_mode=False):`
I can’t match your code for calculating the hyperbolic distance with the mathematical formula. Could you please give me some suggestions about understanding them?

**Comment by zhengzhuoxun** [comment]
Hi, I have the same questions. Have you got the answers? Thank you very much in advance.

**Comment by faye0078** [comment]
have the question too.
