### ISSUE TITLE
How to do inferencing?

### ISSUE THREAD

**Issue by Risho92** [HazyResearch/KGEmb#5]
I am new to knowledge graph. I trained and tested ATTE model and the results look promising. Is it possible to provide the instructions to use this for inferencing?

**Comment by ines-chami** [comment]
The test.py script has an example for how to do inferencing. The different steps are:
1. Load the data in a KGDataset object (see datasets/kg_dataset.py)
2. Create the KG model (see models/)
3. Given a query (head, relation, ?) or (?, relation, tail), predict the rank of the missing entity and compute the evaluation metrics. The function compute_metrics does both prediction and evaluation at the same time:
https://github.com/HazyResearch/KGEmb/blob/c0b7d90701ca8c939285a63c5e277469139d31d4/models/base.py#L185

**Comment by Risho92** [comment]
Thank you
