### ISSUE TITLE
the global graph curvature ξG

### ISSUE THREAD

**Issue by xjzhao001** [HazyResearch/KGEmb#8]
Thank you very much for sharing the code. I have a small question, where is the code for estimating the global graph curvature ξG?

**Comment by ines-chami** [comment]
Here is an example implementation:
<img width="743" alt="Screen Shot 2020-12-02 at 4 19 53 PM" src="https://user-images.githubusercontent.com/13433391/100892055-37d1f480-34ba-11eb-822f-acbb29fb6ca1.png">

This is simply applying Equation (3) in the product-space paper ([https://openreview.net/pdf?id=HJxeWnCcF7](https://openreview.net/pdf?id=HJxeWnCcF7))
