### ISSUE TITLE
test file

### ISSUE THREAD

**Issue by qiaoxiaoqiao1** [HazyResearch/KGEmb#9]
How should I run test.py after I complete the usage stage, should I change the "model_dir" in "parser.add_argument(
    '--model_dir',
    help="Model path"
)" ?

Besides, how should I get the link prediction result? It looks like you only provide MRR and H@10, if given 2 entities, I want to get a relation, how should I get it?

**Comment by qiaoxiaoqiao1** [comment]
I attach a screen shot for test.py here
![Screen Shot 2021-03-06 at 10 52 42 AM](https://user-images.githubusercontent.com/42417485/110214537-ac764f80-7e6a-11eb-83a2-ec1caa1283bc.png)

**Comment by ines-chami** [comment]
Please use: 
`python test.py --help`
for help with command line usage. This may be useful as well: https://docs.python.org/3/howto/argparse.html

The test script returns all metrics (MRR, H@{1,3,10}).
https://github.com/HazyResearch/KGEmb/blob/f52b1f83e1aa063e72d9cd4392e6b89cbf85d56a/utils/train.py#L35
